config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :index, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  root 'sessions#new'

  resources :bands
end

app/models/album.rb
class Album < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_reader :password

  validates :email, :session_token, :password_digest, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in? #makes it available to the view.

  def logged_in?
    current_user != nil
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    session[:session_token] = @user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  #DO THIS LATER:
  #redirect to sign up unless logged in, add a buton on login to sign_up.
  #Inside the site, where can anyone go, and where can only logged in people go?

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_logged_in


  def index
    @bands = Band.order(:id)
    render :index
  end

  def new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def show
    @band = Band.find_by(id: params[:id])
    render :show
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])

    @band.update(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      render plain: "FAILED TO UPDATE !"
    end
  end

  def destroy

  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email],
                                     params[:user][:password])

    if @user
      #what happens here? Log in, then redirect to show.
      login!(@user)
      # fail
      redirect_to user_url(@user)
    else
      flash[:errors] = ["Wrong Credentials"]
      redirect_to new_session_url
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

  private

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only: [:index,:show]

  def index
    @users = User.all
    render json: @users
  end

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url, method: :get
    end
  end

  def show
    @user = User.find(params[:id])
    if @user
      render :show
    else
      render Plain: 'User not FOUND!!!!AAAHAAHAHAHAHAHA'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type=\"hidden\"
             name=\"authenticity_token\"
             value=\" <%= form_authenticity_token %> \">".html_safe
   end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bands/edit.html.erb
<h1>Change the name of the band.</h1>

<form action=" <%= band_url(@band) %> " method="post">
  <input type="hidden" name="_method" value="PATCH">
  <%= auth_token %>
  <label for="name"> New Name </label>
  <input id="name" type="text" name="band[name]" value=" <%= @band.name %> ">

  <input type="submit" value="Change!">
</form>

app/views/bands/index.html.erb
<h1>All of the bands!!!!!</h1>

<form action=" <%= new_band_url %> " method="get">
  <%= auth_token %>
  <input type="submit" value="create a new band">
</form>


<table>
  <th>Band ID </th>
  <th>Band Name</th>
  <th>View</th>
  <th>Edit</th>
  <% @bands.each do |band| %>
  <tr>
    <td> <%= band.id %> </td>
    <td> <%= band.name %> </td>
    <td>
          <form action=" <%= band_url(band) %> " method="get">
            <input type="submit" value="View">
            <%= auth_token %>
          </form>
    </td>
    <td>
          <form action=" <%= edit_band_url(band) %> " method="get">
            <input type="submit" value="Edit">
            <%= auth_token %>
          </form>
    </td>
  </tr>
  <% end %>
</table>

app/views/bands/new.html.erb
<h1>Create a new band.</h1>

<%= render 'shared/errors' %>

<form action=" <%= bands_url %> " method="post">
  <!-- <input type="hidden" name="_method" value="PATCH"> -->
  <%= auth_token %>
  <label for="name"> New Name </label>
  <input id="name" type="text" name="band[name]">

  <input type="submit" value="Create">
</form>

app/views/bands/show.html.erb
<h1> <%= @band.name %> </h1>

<p>This is the page for <%= @band.name %>. They're the best! </p>

<form action=" <%= bands_url %>  " method="get">
  <%= auth_token %>
  <input type="submit" value="back to bands">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <h1>THE BOMBEST MUSIC WEBSITE EVER</h1>

    <header class="group">
      <% if logged_in? %>
        <form action="<%=session_url%>" method="post">
            <input type="hidden" name="_method" value="delete">
            <%= auth_token %>
            <p>You are logged in as <%= current_user.email %>.</p>
            <input id="in-button" type="submit" value="log out">
        </form>

        <form action=" <%= user_url(current_user) %> " method="get">
            <%= auth_token %>
            <input type="submit" value="homepage">
        </form>

      <% else %>

        <form action=" <%= new_session_url %> " method="get">
            <%= auth_token %>
            <input id="out-button" type="submit" value="login">
        </form>

        <form action=" <%= new_user_url %> " method="get">
            <%= auth_token %>
            <input id="out-button" type="submit" value="sign the 'f' up">
        </form>

      <% end  %>

    </header>

    <%= yield %>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end  %>

app/views/users/new.html.erb
<h1>New User. Welome to the Music Sharing Website</h1>

<p>Please sign up here.</p>

 <%= render 'shared/errors' %>

<form action=" <%= users_url %> " method="post">

  <label for="email">Email Address:</label>
  <input id="email" type="text" name="user[email]">

  <label for="password">Password(Must be six characters)</label>
  <input id="password" type="text" name="user[password]">

  <%= auth_token %>

  <input id='signup' type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h1>Welcome to the greatest m*********ing music website you'll ever visit in
  your entire life, <%= @user.email %>!</h1>

<form action=" <%= bands_url %> " method="get">
  <%= auth_token %>
  <input type="submit" value="see the bands">
</form>